### ISSUE TITLE
Command always fail

### ISSUE THREAD

**Issue by smith64fx** [guru-digital/ispconfig-cli#3]
So when I try to add a client for example (All the parameters are given), The CLI always give me "failed".

ispconfig-cli clientAdd "Max Muster" "Muster AG" "maxmustermann" "h52j   3ha&22" "muster@gmx.de" "0183821482"

![image](https://cloud.githubusercontent.com/assets/3246782/7429899/64aa1e92-f00a-11e4-9957-7d82f10532cd.png)

**Comment by smith64fx** [comment]
A Verbose output says:

`Failed
Error: web_php_options_notempty<br />
ssh_chroot_notempty<br />

#0 [internal function]: SoapClient->__call('client_add', Array)
#1 [internal function]: SoapClient->client_add('8fcf8bc9e7065b4...', NULL, Array)
#2 /opt/ispconfig-cli/vendor/gdm/ispconfig-soap-client/GDM/ISPConfig/AbstractSoapClient.php(195): call_user_func_array(Array, Array)
#3 /opt/ispconfig-cli/vendor/gdm/ispconfig-soap-client/GDM/ISPConfig/SoapClient.php(374): GDM\ISPConfig\AbstractSoapClient->makeCall('client_add', '8fcf8bc9e7065b4...', NULL, Array)
#4 [internal function]: GDM\ISPConfig\SoapClient->clientAdd('Max Muster', 'Muster AG', 'maxmustermann', 'h52j   3ha&22', 'muster@gmx.de', '0183821482', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
#5 /opt/ispconfig-cli/src/GDM/ISPConfigCli/Command.php(148): call_user_func_array(Array, Array)
#6 /opt/ispconfig-cli/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): GDM\ISPConfigCli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /opt/ispconfig-cli/src/GDM/ISPConfigCli/Command.php(36): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /opt/ispconfig-cli/vendor/symfony/console/Symfony/Component/Console/Application.php(874): GDM\ISPConfigCli\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /opt/ispconfig-cli/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(GDM\ISPConfigCli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /opt/ispconfig-cli/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/ispconfig-cli/bin/ispconfig-cli(60): Symfony\Component\Console\Application->run()
#12 {main}`
